---
# This playbook
# 1. Installs podman
# 2. Pulls container image that runs dnsmasq
# 3. Assigns IP address to an interface specified; the specified interface will listen to DHCP requests
# 4. Creates the dnsmasq.conf file that will be used by dnsmasq
# 5. Creates container with systemd file generated that allows dnsmasq container to run as a service across reboots
# NOTE: Update values for the variables below before running the playbook
- name: dhcp server setup playbook
  hosts: "{{ target }}"
  roles:
    - role: install_packages
      become: yes
      vars:
        pkg: podman
    - role: container_images_pull
      vars:
        image_name: 4km3/dnsmasq
        image_tag: 2.86-r0
        registry_username:
        registry_password:
        registry_name: docker.io
        registry_auth_file: /tmp/auth.json
    - role: ip_address_assign
      become: yes
      vars:
        if_name: eno12409
        ip4_address: 172.168.40.6/24
    - role: dhcp_config_file
      become: yes
      vars:
        custom_dns_hostnames: [master-node-1,master-node-2,master-node-3,worker-node-1,worker-node-2,worker-node-3]
        default_gateway: 192.168.19.1
        dhcp_conf_dir: /etc/dnsmasq/
        dhcp_conf_file: dnsmasq.conf
        dhcp_range: 192.168.19.20,192.168.19.125,12h
        fqdn_name: cp4na.bos2.lab
        include_custom_fqdn: yes
        ipaddr_hosts: [192.168.19.74,192.168.19.73,192.168.19.57,192.168.19.101,192.168.19.43,192.168.19.71]
        listening_interface_ip_address: 192.168.19.11
        listening_interface_name: eno12399
        macaddr_hosts: ["b4:96:91:d6:7a:a4","b4:96:91:d6:7b:48","b4:96:91:d6:7a:94","b4:96:91:d6:7a:c0","b4:96:91:d6:7f:88","b4:96:91:d6:7f:ec"]
        subnet_mask: 255.255.255.128
    - role: container_systemd_service
      become: yes
      vars:
        cap_add_list:
          - NET_ADMIN
        command: -q --conf-file=/opt/dnsmasq/dnsmasq.conf --dhcp-broadcast --log-facility=- -k
        image: 4km3/dnsmasq:2.86-r0
        restart_policy: on-failure
        network_mode:
          - host
        svc_name: dnss
        system_path: /etc/systemd/system/
        volumes_list:
          - /etc/dnsmasq/:/opt/dnsmasq/:Z
